// packages/sub-vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
</script>

<template>
  <div class="vue-app">
    <h2 style="color: #42b883">Vue Sub-App</h2>
    <p>This is the Vue micro-frontend, loaded by qiankun.</p>
    <button class="btn" @click="count++">Count: {{ count }}</button>
  </div>
</template>

<style scoped>
.vue-app {
  padding: 24px;
  font-family: sans-serif;
}
.btn {
  padding: 8px 24px;
  font-size: 16px;
  cursor: pointer;
  background: #42b883;
  color: #fff;
  border: none;
  border-radius: 6px;
}
</style>

// packages/sub-react/src/App.tsx
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{ padding: 24, fontFamily: "sans-serif" }}>
      <h2 style={{ color: "#1677ff" }}>React Sub-App</h2>
      <p>This is the React micro-frontend, loaded by qiankun.</p>
      <button
        onClick={() => setCount((c) => c + 1)}
        style={{
          padding: "8px 24px",
          fontSize: 16,
          cursor: "pointer",
          background: "#1677ff",
          color: "#fff",
          border: "none",
          borderRadius: 6,
        }}
      >
        Count: {count}
      </button>
    </div>
  );
}
